extends Node

signal disc_thrown(origin: Vector2, direction: Vector2)
signal disc_bounced(position: Vector2, bounces_left: int, shake_intensity: float)
signal disc_caught()
signal disc_recalled()
signal disc_blocked(perfect: bool)
signal enemy_died(enemy: Node2D)
signal damage_dealt(position: Vector2, amount: float, is_crit: bool)
signal player_damaged(hp: int)
signal player_died()
signal wave_started(wave_number: int)
signal wave_cleared(wave_number: int)
signal level_completed()
signal boss_phase_changed(phase: int)
signal upgrade_selected(upgrade_id: String)
signal combo_changed(mult: float)
signal currency_collected(amount: int)
